baseURL = 'https://pablo-johnson.github.io/carlosjohnson.github.io/'
theme = 'PaperMod'
# canonifyURLs = false
buildFuture = true

[services]
  [services.googleAnalytics]
    id = 'G-FHH7XVEBFG'

# Configuracion Multilingue: Alemán por defecto
defaultContentLanguage = 'de'

[languages]
  [languages.de]
    languageCode = 'de-DE'
    languageName = 'Deutsch'
    weight = 1
    title = 'Carlos Johnson'
    [languages.de.params]
      description = 'Klassischer Geiger und Dozent'

  [languages.es]
    languageCode = 'es-ES'
    languageName = 'Español'
    weight = 2
    title = 'Carlos Johnson'
    [languages.es.params]
      description = 'Violinista Clásico y Profesor'

[params]
  defaultTheme = 'light'
  ShowShareButtons = false
  ShowReadingTime = false
  [params.profileMode]
    enabled = true

# --- MENUS ---
[languages.de.menu]
  [[languages.de.menu.main]]
    name = "Biografie"
    url = "about/"
    weight = 1
  [[languages.de.menu.main]]
    identifier = "multimedia"
    name = "Multimedia"
    weight = 4
  [[languages.de.menu.main]]
    name = "Imágenes"
    url = "images/"
    parent = "multimedia"
    weight = 1
  [[languages.de.menu.main]]
    name = "Videos"
    url = "videos/"
    parent = "multimedia"
    weight = 2
  [[languages.de.menu.main]]
    name = "Audios"
    url = "audios/"
    parent = "multimedia"
    weight = 3
  [[languages.de.menu.main]]
    name = "Konzerte"
    url = "concerts/"
    weight = 3
  [[languages.de.menu.main]]
    name = "Lehre"
    url = "teaching/"
    weight = 2
  [[languages.de.menu.main]]
    name = "Kontakt"
    url = "contact/"
    weight = 5

[languages.es.menu]
  [[languages.es.menu.main]]
    name = "Biografía"
    url = "about/"
    weight = 1
  [[languages.es.menu.main]]
    identifier = "multimedia"
    name = "Multimedia"
    weight = 4
  [[languages.es.menu.main]]
    name = "Imágenes"
    url = "images/"
    parent = "multimedia"
    weight = 1
  [[languages.es.menu.main]]
    name = "Videos"
    url = "videos/"
    parent = "multimedia"
    weight = 2
  [[languages.es.menu.main]]
    name = "Audios"
    url = "audios/"
    parent = "multimedia"
    weight = 3
  [[languages.es.menu.main]]
    name = "Conciertos"
    url = "concerts/"
    weight = 3
  [[languages.es.menu.main]]
    name = "Docencia"
    url = "teaching/"
    weight = 2
  [[languages.es.menu.main]]
    name = "Contacto"
    url = "contact/"
    weight = 5